/* ═══════════════════════════════════════════════════════════════════════
   CLIENTES CANCELADOS — derivado de Churn > Análisis DATA
   GENERADO — no editar a mano.
   Regenerar con: python scripts/gen-churn-cancelados.py

   Los reportes semanales viven dentro de app/churn/page.tsx, que es un
   componente 'use client' y no los exporta. Este módulo extrae solo los
   nombres de clientes cancelados para que el backend pueda consumirlos:
   lib/elegibilidad.ts los usa para no generar Actividades SAC sobre
   cuentas ya canceladas.
═══════════════════════════════════════════════════════════════════════ */

export interface ClienteCancelado {
  cliente: string
  periodo: string
}

export const CLIENTES_CANCELADOS: ClienteCancelado[] = [
  { cliente: '10 Experiences Tour', periodo: 'Abril 2026' },
  { cliente: '3DX', periodo: 'Semana 11 · Jul 2026' },
  { cliente: 'Abelyne Inc', periodo: 'Semana 1 · Jun 2026' },
  { cliente: 'Abkam', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Adim ecosistema', periodo: 'Semana 9 · Jun 2026' },
  { cliente: 'Alamo Seguros', periodo: 'Semana 13 · Jul 2026' },
  { cliente: 'Aristea', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'BDM LAB', periodo: 'Abril 2026' },
  { cliente: 'Boma Coaching & Analysis', periodo: 'Abril 2026' },
  { cliente: 'Bondeados Grupo Revilla', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Casa Santiago', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'CITUR', periodo: 'Abril 2026' },
  { cliente: 'COESPRO', periodo: 'Semana 2 · Ago 2026' },
  { cliente: 'Colegio NWL - Milenio', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Comercial Regasa', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Corporativo Videci', periodo: 'Semana 11 · Jul 2026' },
  { cliente: 'Creativa', periodo: 'Semana 14 · Jul 2026' },
  { cliente: 'Custodias RJ', periodo: 'Semana 3 · Ago 2026' },
  { cliente: 'Dinosaurio Hosting Mexico', periodo: 'Semana 12 · Jul 2026' },
  { cliente: 'El Surtidor', periodo: 'Semana 11 · Jul 2026' },
  { cliente: 'Embler Autopartes', periodo: 'Semana 4 · Mayo 2026' },
  { cliente: 'EMPODERA SALUD', periodo: 'Semana 11 · Jul 2026' },
  { cliente: 'ENVIRONET', periodo: 'Semana 14 · Jul 2026' },
  { cliente: 'ESG Servicios Migratorios', periodo: 'Semana 2 · Ago 2026' },
  { cliente: 'Estradata', periodo: 'Abril 2026' },
  { cliente: 'Estradata MH', periodo: 'Abril 2026' },
  { cliente: 'EXTIN-SON', periodo: 'Abril 2026' },
  { cliente: 'Filo', periodo: 'Abril 2026' },
  { cliente: 'Finaura', periodo: 'Semana 1 · Jun 2026' },
  { cliente: 'GROW Real Estate', periodo: 'Semana 12 · Jul 2026' },
  { cliente: 'GRUPO BC BIENES RAICES', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Grupo CBCA', periodo: 'Semana 12 · Jul 2026' },
  { cliente: 'Grupo Empresarial Moran', periodo: 'Semana 2 · Jun 2026' },
  { cliente: 'GRUPO GEVHE', periodo: 'Semana 13 · Jul 2026' },
  { cliente: 'GRUPO REACCION GPS', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Grupo Sirob', periodo: 'Semana 13 · Jul 2026' },
  { cliente: 'Grupo Taneg', periodo: 'Semana 12 · Jul 2026' },
  { cliente: 'GTC - CENTRO MAX', periodo: 'Semana 4 · Mayo 2026' },
  { cliente: 'GTC - FORUM', periodo: 'Semana 4 · Mayo 2026' },
  { cliente: 'GTC - NAVA', periodo: 'Semana 4 · Mayo 2026' },
  { cliente: 'Holton', periodo: 'Semana 1 · Jun 2026' },
  { cliente: 'Hospital Merlos', periodo: 'Abril 2026' },
  { cliente: 'Houses Land', periodo: 'Semana 12 · Jul 2026' },
  { cliente: 'HOWARD Corporativo Inmobiliario', periodo: 'Semana 2 · Jun 2026' },
  { cliente: 'INVEXIO', periodo: 'Semana 13 · Jul 2026' },
  { cliente: 'IT GREEN', periodo: 'Abril 2026' },
  { cliente: 'IT REINGENIERIAS', periodo: 'Cierre Junio 2026' },
  { cliente: 'JAD Suministros', periodo: 'Abril 2026' },
  { cliente: 'Kayrot', periodo: 'Semana 9 · Jun 2026' },
  { cliente: 'KINDEMEX', periodo: 'Abril 2026' },
  { cliente: 'KUMON LA PRADERA', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Lunah Eco-resorts CDMX', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Madero Restaurante', periodo: 'Semana 2 · Jun 2026' },
  { cliente: 'MIRA DIAMANTE SOLUCLOUD', periodo: 'Semana 11 · Jul 2026' },
  { cliente: 'MxBoxing', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Neek Tulum', periodo: 'Abril 2026' },
  { cliente: 'PAN AMERICAN', periodo: 'Semana 14 · Jul 2026' },
  { cliente: 'Pasteur Soft', periodo: 'Semana 14 · Jul 2026' },
  { cliente: 'Persianas Marais', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Petroil - Prebiem Oceanica', periodo: 'Semana 4 · Mayo 2026' },
  { cliente: 'PlastilinaBTl', periodo: 'Semana 5 · Mayo 2026' },
  { cliente: 'Price Logistics', periodo: 'Abril 2026' },
  { cliente: 'Probemedic Farmacias', periodo: 'Semana 11 · Jul 2026' },
  { cliente: 'Prya grupo inmobiliario', periodo: 'Semana 3 · Ago 2026' },
  { cliente: 'Quality Lema', periodo: 'Semana 2 · Ago 2026' },
  { cliente: 'QuikPeso', periodo: 'Semana 14 · Jul 2026' },
  { cliente: 'Quimicos XY', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Reactor', periodo: 'Semana 14 · Jul 2026' },
  { cliente: 'Red t', periodo: 'Semana 2 · Jun 2026' },
  { cliente: 'RELIABLEGLOBALMANAGEMENTLME', periodo: 'Cierre Junio 2026' },
  { cliente: 'Remax Lafueya', periodo: 'Abril 2026' },
  { cliente: 'Remax Quality', periodo: 'Semana 2 · Jun 2026' },
  { cliente: 'RESTA TOOLS', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'ROAL TRANSPORTES', periodo: 'Semana 11 · Jul 2026' },
  { cliente: 'Rodolfo Guerrero Scott', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'ROYAL HOME', periodo: 'Abril 2026' },
  { cliente: 'SalvadoreX', periodo: 'Semana 2 · Jun 2026' },
  { cliente: 'SAMALAB', periodo: 'Semana 4 · Mayo 2026' },
  { cliente: 'satvpafc', periodo: 'Semana 9 · Jun 2026' },
  { cliente: 'SEDEMEX', periodo: 'Semana 8 · Jun 2026' },
  { cliente: 'Servitaxi Rincón de Palma Real', periodo: 'Semana 13 · Jul 2026' },
  { cliente: 'SG LOCALIZACION', periodo: 'Semana 4 · Mayo 2026' },
  { cliente: 'Torre Himalaya', periodo: 'Semana 14 · Jul 2026' },
  { cliente: 'TRIBECA HAIR STUDIO', periodo: 'Abril 2026' },
  { cliente: 'TURISMO NICETRIP', periodo: 'Semana 5 · Mayo 2026' },
  { cliente: 'Valdi abogados', periodo: 'Abril 2026' },
  { cliente: 'ZD - Grupo RH', periodo: 'Abril 2026' },
  { cliente: 'ZD - Midstorage', periodo: 'Semana 11 · Jul 2026' },
  { cliente: '— Suspendido→Cancelado · CORRUBOX MEXICO', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '— Suspendido→Cancelado · DISTRIB. MEDICA ONCOPHARMAX', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '— Suspendido→Cancelado · Globovista', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '— Suspendido→Cancelado · Grúas Gutigon', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '— Suspendido→Cancelado · Roal Travel', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '— Suspendido→Cancelado · Taxis Unidos Camargo', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '— Suspendido→Cancelado · WALT AND MACON', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '— Suspendido→Cancelado · Xelbor Transfer', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '🔝 Armonmex', periodo: 'Semana 8 · Jun 2026' },
  { cliente: '🔝 Bliss crédito libre', periodo: 'Semana 13 · Jul 2026' },
  { cliente: '🔝 Centro Mexicano de Psicología Integrativa CEMEPI', periodo: 'Semana 3 · Ago 2026' },
  { cliente: '🔝 HostPal', periodo: 'Semana 14 · Jul 2026' },
  { cliente: '🔝 Torre 2 - Via Montejo', periodo: 'Semana 2 · Ago 2026' },
  { cliente: '🔝 TURBODAYS', periodo: 'Semana 2 · Jun 2026' },
  { cliente: '🔝 Yapp', periodo: 'Semana 12 · Jul 2026' },
  { cliente: '🔝 ZD - Grupo Liber', periodo: 'Cierre Junio 2026' },
]
